#!D:\AppTag_Projects\Reddit_Acc_gen\v_reddit_acc\Scripts\python.exe
# Copyright 2014-2017, Damian Johnson and The Tor Project
# See LICENSE for licensing information

import stem.interpreter

if __name__ == '__main__':
  stem.interpreter.main()
